In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

## Reading in Data etc

https://www.usek.edu.lb/Content/Assets/20240205WorkspaceWAinstrumentCode.pdf

In [2]:
import eikon as ek
ek.set_app_key('9fbc5c01e4e34244bb166389f0515e16d536af6c')

In [239]:
NASDAQ_Names = ['MSFT.O','NVDA.O','AAPL.O','AMZN.O','GOOGL.O', 'META.O', 'TSLA.O', 'AVGO.O', 'BRKb.O', 'WMT.O', 'JPM.O', 'V.O', 'LLY.O', 'MA.O', 'NFLX.O', 'XOM.O', 'ORCL.O', 'COST.O', 'HD.O', 'PG.O', 'JNJ.O', 'BAC.O', 'ABBV.O', 'KO.O', 'UNH.O', 'CRM.O', 'TMUS.O', 'PM.O', 'WFC.O', 'CVX.O']
NYSE_Names = ['BRKb.N', 'WMT.N', 'JPM.N', 'V.N', 'LLY.N', 'MA.N', 'XOM.N', 'ORCL.N', 'HD.N', 'PG.N', 'JNJ.N', 'BAC.N', 'ABBV.N', 'KO.N', 'UNH.N', 'CRM.N', 'PM.N', 'WFC.N', 'CVX.N']

In [240]:
# ────────────────────────────────
# 30-largest U.S. companies
# ────────────────────────────────
US_IV_RICS = {
    "MSFT": "MSFTATMIV.U",   # Microsoft          :contentReference[oaicite:1]{index=1}
    "NVDA": "NVDAATMIV.U",   # Nvidia             :contentReference[oaicite:2]{index=2}
    "AAPL": "AAPLATMIV.U",   # Apple              :contentReference[oaicite:3]{index=3}
    "AMZN": "AMZNATMIV.U",   # Amazon             :contentReference[oaicite:4]{index=4}
    "GOOGL": "GOOGLATMIV.U", # Alphabet-A         :contentReference[oaicite:5]{index=5}
    "META": "METAATMIV.U",   # Meta Platforms
    "TSLA": "TSLAATMIV.U",   # Tesla
    "AVGO": "AVGOATMIV.U",   # Broadcom
    "BRKb": "BRKbATMIV.U",   # Berkshire Hathaway-B :contentReference[oaicite:6]{index=6}
    "WMT": "WMTATMIV.U",     # Walmart
    "JPM": "JPMATMIV.U",     # JPMorgan Chase
    "V":   "VATMIV.U",       # Visa A
    "LLY": "LLYATMIV.U",     # Eli Lilly          :contentReference[oaicite:7]{index=7}
    "MA":  "MAATMIV.U",      # Mastercard A
    "NFLX":"NFLXATMIV.U",    # Netflix
    "XOM": "XOMATMIV.U",     # Exxon Mobil
    "ORCL":"ORCLATMIV.U",    # Oracle
    "COST":"COSTATMIV.U",    # Costco
    "HD":  "HDATMIV.U",      # Home Depot
    "PG":  "PGATMIV.U",      # Procter & Gamble
    "JNJ": "JNJATMIV.U",     # Johnson & Johnson
    "BAC": "BACATMIV.U",     # Bank of America
    "ABBV":"ABBVATMIV.U",    # AbbVie
    "KO":  "KOATMIV.U",      # Coca-Cola
    "UNH": "UNHATMIV.U",     # UnitedHealth
    "CRM": "CRMATMIV.U",     # Salesforce
    "TMUS":"TMUSATMIV.U",    # T-Mobile US
    "PM":  "PMATMIV.U",      # Philip Morris Int’l
    "WFC": "WFCATMIV.U",     # Wells Fargo
    "CVX": "CVXATMIV.U"      # Chevron
}

In [223]:
US_Top30_df_NYSE, e = ek.get_data(
                    US_Top_30_Names_NYSE,
                    fields=['TR.OPENPRICE.Date','TR.High', 'TR.Low', 'TR.Open', 'TR.Close', 'TR.Volume'],
                    parameters={'SDate': '2019-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'}
)

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

In [38]:
SP_indices = ['.SPX']
fields = ['TR.Close', 'TR.Close.Date']
SP500, e = ek.get_data(SP_indices, fields = fields, parameters = {'SDate': '2005-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'})
SP500.head()

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

  Instrument  Price Close                  Date
0       .SPX      1202.08  2005-01-03T00:00:00Z
1       .SPX      1188.05  2005-01-04T00:00:00Z
2       .SPX      1183.74  2005-01-05T00:00:00Z
3       .SPX      1187.89  2005-01-06T00:00:00Z
4       .SPX      1186.19  2005-01-07T00:00:00Z

In [41]:
SP500.set_index('Date', inplace = True)
SP500.index = pd.to_datetime(SP500.index).to_period('D')
SP500.to_csv('SP500_2005_2025.CSV')

C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\2433216771.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  SP500.index = pd.to_datetime(SP500.index).to_period('D')

In [39]:
SP_indices = ['.5SP10', '.5SP25', '.5SP40', '.5SP35', '.5SP55','.5SP60', '.5SP15']

In [ ]:
SP_500_Sector_dfs = {}
for i in SP_indices:
    name = str(i) + '_df'
    df = SP_500_2005_2025.groupby('Instrument').get_group(str(i))
    df.set_index('Date', inplace = True)
    df.index = pd.to_datetime(df.index).to_period('D')
    SP_500_Sector_dfs[name] = df
    df.to_csv(f'SP500_Sector_{name}_2005_2025.csv')

C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')
C:\Users\Phillip\AppData\Local\Temp\ipykernel_30116\1105127967.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.index = pd.to_datetime(df.index).to_period('D')

In [36]:
SP_500_Sector_dfs['.5SP35_df']

           Instrument  Close Price
Date
2005-01-03     .5SP35     346.8074
2005-01-04     .5SP35     344.2478
2005-01-05     .5SP35     343.1532
2005-01-06     .5SP35      345.624
2005-01-07     .5SP35     345.7193
...               ...          ...
2025-05-05     .5SP35    1608.2907
2025-05-06     .5SP35    1563.9829
2025-05-07     .5SP35    1576.6565
2025-05-08     .5SP35    1562.2415
2025-05-09     .5SP35    1545.0873

[5310 rows x 2 columns]

In [241]:
US_Top30_ATM_Vols_df ,e = ek.get_data(
                        list(US_IV_RICS.values()),
                        fields = ['TR.30DAYATTHEMONEYIMPLIEDVOLATILITYINDEXFORPUTOPTIONS.Date',
                                'TR.30DAYATTHEMONEYIMPLIEDVOLATILITYINDEXFORPUTOPTIONS'],
                        parameters= {'SDate': '2019-01-01',
                                    'EDate': '2025-05-11',
                                    'Frq':'D'}) 

US_Top30_ATM_Vols_df = US_Top30_ATM_Vols_df.rename(columns={v: k for k, v in IDX_IV_RICS.items()})

c:\Users\Phillip\AppData\Local\Programs\Python\Python39\lib\site-packages\eikon\data_grid.py:255: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

In [35]:
big_df = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SP500_2005_2025.csv', parse_dates = True)
a = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SkewX_2005_2025.csv', parse_dates = True).dropna()
#b = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\RVol_2005_2025.csv', parse_dates=True).dropna()
e = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\VIX_2005_2025.csv', parse_dates = True)
f = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\VVIX_2006_2025.csv', parse_dates = True)

abc = [big_df, a,e, f]
df_dict = {}
length = {}
for i in abc:
    df_copy = i.copy()
    df_copy.reset_index(inplace= True)
    df_copy = df_copy.drop_duplicates(subset=['Date']).set_index('Date')
    df_copy.index = pd.to_datetime(df_copy.index).to_period('D')
    df_copy = df_copy.loc['2006-03-01':'2025-05-05']
    name = df_copy['Instrument'].iloc[0].strip('.')
    df_copy.drop(columns = ['Instrument', 'index'], inplace = True)
    df_copy.columns = [name]
    df_dict[name] = df_copy
    length[name] = (df_copy.shape[0])

In [ ]:
smallest_ = min(length, key = length.get)
df2_dict = {}

for i in df_dict:
    if i != smallest_:
        df_mask = df_dict[i].index.difference(df_dict[smallest_].index)
        df = df_dict[i].drop(mask)
        df_dict[smallest_][i] = df
    else:
        pass

g = df_dict[smallest_].dropna().drop_duplicates(keep='first')

In [ ]:
g = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SP_VIX_VVIX_SKEW_RV_2006_2025.csv', parse_dates = True, index_col='date')
g.drop_duplicates(inplace = True)
g['Returns'] = np.log(g['SPX'] / g['SPX'].shift(1)) * 100
g.dropna(inplace = True)
g['GPR'] = d['GPR'].reindex(g.index, method = 'ffill')
g['month value'] = g.index.to_period('M').start_time
g.to_csv('SP_VIX_VVIX_SKEW_RV_2006_2025_with_GPR.csv')

In [ ]:

g.to_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SP_VIX_VVIX_SKEW_2006_2025.csv')

              VVIX      SPX   SKEWX    VIX
Date
2006-03-06   71.73  1278.26  116.60  12.74
2006-03-15   15.71  1303.02  119.12  11.35
2006-03-16   27.94  1305.33  142.02  11.98
2006-03-17   28.60  1307.25  130.06  12.12
2006-03-20   37.93  1305.08  124.39  11.79
...            ...      ...     ...    ...
2025-04-29  101.31  5560.83  134.29  24.17
2025-04-30  102.29  5569.06  132.73  24.70
2025-05-01  102.31  5604.14  134.07  24.60
2025-05-02   97.26  5686.67  134.78  22.68
2025-05-05  101.17  5650.38  134.12  23.64

[4754 rows x 4 columns]

In [99]:
g[g.duplicated(keep=False)]

              VVIX      SPX   SKEWX    VIX
Date
2021-09-03  105.48  4535.43  162.27  16.41
2021-09-06  105.48  4535.43  162.27  16.41
2021-11-24  110.48  4701.46  148.15  18.58
2021-11-25  110.48  4701.46  148.15  18.58
2021-12-23  120.46  4725.79  150.26  17.96
2021-12-24  120.46  4725.79  150.26  17.96
2022-01-14  117.57  4662.85  133.85  19.19
2022-01-17  117.57  4662.85  133.85  19.19
2022-02-18  133.64  4348.87  128.36  27.75
2022-02-21  133.64  4348.87  128.36  27.75
2022-04-14  114.75  4392.59  134.39  22.70
2022-04-15  114.75  4392.59  134.39  22.70

In [75]:
mask = df_dict['SPX'].index.difference(df_dict[smallest_].index)
sp_2 = df_dict['SPX'].drop(mask)

In [79]:
sp_2['VVIX'] = df_dict['VVIX'].values

In [84]:
sp_2[sp_2.duplicated(keep=False)]

                SPX    VVIX
Date
2021-09-03  4535.43  105.48
2021-09-06  4535.43  105.48
2021-11-24  4701.46  110.48
2021-11-25  4701.46  110.48
2021-12-23  4725.79  120.46
2021-12-24  4725.79  120.46
2022-01-14  4662.85  117.57
2022-01-17  4662.85  117.57
2022-02-18  4348.87  133.64
2022-02-21  4348.87  133.64
2022-04-14  4392.59  114.75
2022-04-15  4392.59  114.75
2022-05-27  4158.24   93.66
2022-05-30  4158.24   93.66
2022-06-17  3674.84  110.06
2022-06-20  3674.84  110.06
2022-07-01  3825.33   85.51
2022-07-04  3825.33   85.51
2022-09-02  3924.26   89.19
2022-09-05  3924.26   89.19

In [70]:
vix_df = df_dict['VIX']
sp_df = df_dict['SPX']
vvix_df = df_dict['VVIX']
skew_df = df_dict['SKEWX']

In [32]:
sp_df.index.difference(skew_df.index)

PeriodIndex(['2011-02-09', '2011-08-29', '2011-10-26', '2011-11-14',
             '2014-04-24', '2014-04-30', '2014-05-01', '2018-05-11',
             '2019-11-20', '2020-02-27', '2023-09-26', '2024-11-29'],
            dtype='period[D]', name='Date')

In [464]:
vix_df.index.difference(sp_df.index)

PeriodIndex(['2011-09-05', '2022-11-24', '2022-12-26', '2023-01-02',
             '2023-01-16', '2023-02-20', '2023-05-29', '2023-06-19',
             '2023-07-04', '2023-09-04', '2023-11-23', '2024-01-15',
             '2024-02-19', '2024-05-27', '2024-06-19', '2024-07-04',
             '2024-09-02', '2024-11-28', '2025-01-09', '2025-01-20',
             '2025-02-17'],
            dtype='period[D]', name='Date')

In [472]:
print(vix_df.shape[0])
print(sp_df.shape[0])

4857
4836

In [457]:
g = df_dict['SPX']
g['VIX'] = df_dict['VIX']['VIX'].values
g['VVIX'] = df_dict['VVIX']['VVIX'].values
g['Skew'] = df_dict['SKEWX']['SKEWX'].values
g['Realized Vol'] = df_dict['RVOL']['RVOL'].values
g

ValueError: Length of values (4857) does not match length of index (4836)

In [451]:
g.drop_duplicates().shape

(4784, 1)

In [384]:
c = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\Citi Suprise Economic Index 2005-2025.csv', parse_dates = True)
d = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\Geopolitical Risk 1985-2025.csv', parse_dates = True)

### To Save

In [ ]:
#Useful for checking what indices are missing
ids = set(CES.index).intersection(set(g.index))
d1 = CES[CES.index.isin(ids)]
d2 = g[g.index.isin(ids)]
CES.index.difference(d1.index)

Index(['2006-04-14', '2006-05-29', '2006-07-04', '2006-09-04', '2006-11-23',
       '2006-12-25', '2007-01-01', '2007-01-02', '2007-01-15', '2007-02-19',
       ...
       '2024-06-19', '2024-07-04', '2024-09-02', '2024-11-28', '2024-12-25',
       '2025-01-01', '2025-01-09', '2025-01-20', '2025-02-17', '2025-04-18'],
      dtype='object', name='Date', length=141)

In [440]:
#Check for Duplicates
VIX_df_mask = VIX_df3.index.duplicated(keep=False)
VIX_df3[VIX_df_mask]

Empty DataFrame
Columns: [Instrument, Price Close]
Index: []

In [ ]:
#Check for Different Entries between 2 Dataframes
VIX_df3.index.difference(g.index)

Index(['Instrument', 'Price Close'], dtype='object')

In [317]:
g = pd.read_csv(r'C:\Users\Phillip\Desktop\Python\Python Notebooks (Mine)\Dispersion\GARCH MIDAS\GARCH Datasets\SP_VIX_VVIX_SKEW_RV_2006_2025.csv', parse_dates = True, index_col='date')
g.drop_duplicates(inplace = True)
g['Returns'] = np.log(g['SPX'] / g['SPX'].shift(1)) * 100
g.dropna(inplace = True)
g['GPR'] = d['GPR'].reindex(g.index, method = 'ffill')
g['month value'] = g.index.to_period('M').start_time
g.to_csv('SP_VIX_VVIX_SKEW_RV_2006_2025_with_GPR.csv')

In [281]:
d.set_index('month', inplace = True)
d.index = pd.to_datetime(d.index).to_period('M')
d

,GPR,GPRT,GPRA,GPRH,GPRHT,GPRHA,SHARE_GPR,N10,SHARE_GPRH,N3H,...,GPRHC_TUN,GPRHC_TUR,GPRHC_TWN,GPRHC_UKR,GPRHC_USA,GPRHC_VEN,GPRHC_VNM,GPRHC_ZAF,var_name,var_label
month,,,,,,,,,,,,,,,,,,,,,
1985-01,102.173378,107.574173,89.647491,87.153206,101.083145,75.144287,3.064572,11584.0,3.143987,10369,...,0.000000,0.028932,0.038577,0.009644,2.941460,0.000000,0.405054,0.221815,NaN,NaN
1985-02,117.102020,126.442726,96.601669,99.552269,127.213127,75.103569,3.512339,10819.0,3.591274,9718,...,0.041161,0.030871,0.000000,0.010290,3.344310,0.072031,0.339576,0.113192,NaN,NaN
1985-03,124.778152,127.070854,116.987274,103.822472,131.811447,78.716949,3.742576,12291.0,3.745318,11214,...,0.017835,0.080257,0.000000,0.044587,3.433208,0.035670,0.312110,0.133761,NaN,NaN
1985-04,87.929001,94.640198,73.757797,74.304153,91.295639,56.713566,2.637328,12816.0,2.680467,11304,...,0.017693,0.079618,0.017693,0.017693,2.397382,0.106157,0.212314,0.088464,NaN,NaN
1985-05,103.262848,111.159782,92.276726,84.364098,101.910835,73.034920,3.097249,13851.0,3.043372,12289,...,0.024412,0.032549,0.008137,0.000000,2.750427,0.089511,0.195297,0.195297,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12,141.996307,128.137695,164.190903,115.802811,113.668541,123.094238,4.259015,14393.0,4.177500,5769,...,0.017334,1.178714,0.190674,1.542728,4.038828,0.017334,0.052002,0.121338,NaN,NaN
2025-01,112.377914,115.281670,109.678535,93.346298,101.755493,95.010590,3.370645,15902.0,3.367398,5969,...,0.016753,0.201039,0.217792,0.837661,3.367398,0.150779,0.000000,0.067013,NaN,NaN
2025-02,136.362961,137.785965,139.510498,88.993057,103.916000,94.465759,4.090049,14792.0,3.210358,5638,...,0.000000,0.283789,0.124158,1.277049,3.192621,0.088684,0.017737,0.000000,NaN,NaN
2025-03,174.650360,194.295029,157.932175,110.495003,135.720184,105.724541,5.238435,16818.0,3.986025,6297,...,0.000000,0.238209,0.158806,1.778625,3.986025,0.238209,0.063522,0.031761,NaN,NaN
2025-04,136.520844,151.314178,132.717972,112.362518,143.497498,107.572189,4.094784,14897.0,4.053394,6143,...,0.000000,0.000000,0.016279,0.048836,0.130230,0.016279,0.000000,0.016279,NaN,NaN

In [294]:
d.loc['2006-03-01':'2025-05-01']['GPR']

month
2006-03     92.797623
2006-04     89.015800
2006-05     85.208778
2006-06    102.572769
2006-07    137.134827
              ...
2024-12    141.996307
2025-01    112.377914
2025-02    136.362961
2025-03    174.650360
2025-04    136.520844
Freq: M, Name: GPR, Length: 230, dtype: float64

In [ ]:
d.index = d.index.to_timestamp()

In [298]:
g.index = g.index.to_timestamp()

,SPX,VIX,VVIX,Skew,Realized Vol,Returns,week,GPR,month value
date,,,,,,,,,
2006-03-07,1275.88,12.66,71.73,116.21,8.67,-0.186364,2006-03-07,92.797623,2006-03-01
2006-03-08,1278.47,12.32,71.73,117.21,8.69,0.202791,2006-03-07,92.797623,2006-03-01
2006-03-09,1272.23,12.68,71.73,114.20,8.37,-0.489278,2006-03-07,92.797623,2006-03-01
2006-03-10,1281.58,11.85,71.73,116.21,8.32,0.732243,2006-03-07,92.797623,2006-03-01
2006-03-13,1284.13,11.37,71.73,116.54,8.35,0.198775,2006-03-07,92.797623,2006-03-01
...,...,...,...,...,...,...,...,...,...
2025-05-05,5650.38,23.64,101.17,134.12,13.66,-0.640204,2025-04-29,136.520844,2025-05-01
2025-05-06,5606.91,24.76,104.32,133.24,13.66,-0.772303,2025-05-06,136.520844,2025-05-01
2025-05-07,5631.28,23.55,99.82,132.21,13.66,0.433700,2025-05-06,136.520844,2025-05-01
2025-05-08,5663.94,22.48,96.29,131.52,13.66,0.578299,2025-05-06,136.520844,2025-05-01
2025-05-09,5659.91,21.90,96.35,128.40,13.66,-0.071177,2025-05-06,136.520844,2025-05-01

In [301]:
g

                SPX    VIX    VVIX    Skew  Realized Vol   Returns       week
date
2006-03-07  1275.88  12.66   71.73  116.21          8.67 -0.186364 2006-03-07
2006-03-08  1278.47  12.32   71.73  117.21          8.69  0.202791 2006-03-07
2006-03-09  1272.23  12.68   71.73  114.20          8.37 -0.489278 2006-03-07
2006-03-10  1281.58  11.85   71.73  116.21          8.32  0.732243 2006-03-07
2006-03-13  1284.13  11.37   71.73  116.54          8.35  0.198775 2006-03-07
...             ...    ...     ...     ...           ...       ...        ...
2025-05-05  5650.38  23.64  101.17  134.12         13.66 -0.640204 2025-04-29
2025-05-06  5606.91  24.76  104.32  133.24         13.66 -0.772303 2025-05-06
2025-05-07  5631.28  23.55   99.82  132.21         13.66  0.433700 2025-05-06
2025-05-08  5663.94  22.48   96.29  131.52         13.66  0.578299 2025-05-06
2025-05-09  5659.91  21.90   96.35  128.40         13.66 -0.071177 2025-05-06

[5004 rows x 7 columns]

In [255]:
asd = g.index - dt.timedelta(g.index.weekday())

TypeError: 'Index' object is not callable

In [ ]:
g.index[0].weekday() - 1

2

In [248]:
g

                SPX    VIX    VVIX    Skew  Realized Vol   Returns
date
2006-03-06  1278.26  12.74   71.73  116.60          8.88       NaN
2006-03-07  1275.88  12.66   71.73  116.21          8.67 -0.001864
2006-03-08  1278.47  12.32   71.73  117.21          8.69  0.002028
2006-03-09  1272.23  12.68   71.73  114.20          8.37 -0.004893
2006-03-10  1281.58  11.85   71.73  116.21          8.32  0.007322
...             ...    ...     ...     ...           ...       ...
2025-05-05  5650.38  23.64  101.17  134.12         13.66 -0.006402
2025-05-06  5606.91  24.76  104.32  133.24         13.66 -0.007723
2025-05-07  5631.28  23.55   99.82  132.21         13.66  0.004337
2025-05-08  5663.94  22.48   96.29  131.52         13.66  0.005783
2025-05-09  5659.91  21.90   96.35  128.40         13.66 -0.000712

[5005 rows x 6 columns]

In [ ]:
bigger_df = pd.merge(big_df, a, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df = pd.merge(bigger_df, b, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df = pd.merge(bigger_df, c, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df = pd.merge(bigger_df, d, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df = pd.merge(bigger_df, e, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df = pd.merge(bigger_df, f, how = 'left', left_on = 'Date', right_on = 'Date')
bigger_df.head()

,Date,Instrument_x,Price Close_x,Instrument_y,Price Close_y,Instrument,Price1
0,2005-01-03,.SPX,1202.08,.SKEWX,118.38,.RVOL,7.92
1,2005-01-04,.SPX,1188.05,.SKEWX,116.03,.RVOL,8.76
2,2005-01-05,.SPX,1183.74,.SKEWX,114.72,.RVOL,8.77
3,2005-01-06,.SPX,1187.89,.SKEWX,114.15,.RVOL,7.97
4,2005-01-07,.SPX,1186.19,.SKEWX,114.95,.RVOL,7.89